name: ci

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest
    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Starting Pulsar Dev Cluster
        uses: docker://apachepulsar/pulsar:2.10.3
        with:
          options: -it
          mount: |
            pulsardata:/pulsar/data
            pulsarconf:/pulsar/conf
          ports: |
            6650:6650
            8080:8080
          command: "bin/pulsar standalone"
      - name: Test with pytest
        run: poetry run pytest tests/
