name: ci

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest
    services:
      pulsar:
        image: keenborder/pulsar_dev:0.0.1
        volumes:
          - pulsardata:/pulsar/data
          - pulsarconf:/pulsar/conf
        ports:
          - 8080:8080
          - 6650:6650
        options:
          -it
    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Test with pytest
        run: poetry run pytest tests/
